# -- name for this stream
name: kafka-stream-merge

# -- the port to use
port: &port 3000

# -- pod count
replicaCount: 1

# -- source topic 1
sourceTopic1:

# -- projection topic 1
sourceTopic1Projection:

# -- source topic 2
sourceTopic2:

# -- projection topic 2
sourceTopic2Projection:

# -- destination topic
destinationTopic:

image:
  # -- the image name to use
  name: osskit/dafka-merge
  # -- the image tag to use
  tag: '0.1'


startupProbe:
  initialDelaySeconds: 60
  httpGet:
    # -- the path for startup check
    path: /ready
    port: *port
livenessProbe:
  initialDelaySeconds: 30
  httpGet:
    # -- the path for liveness check
    path: /ready
    port: *port
readinessProbe:
  httpGet:
    # -- the path for readiness check
    path: /ready
    port: *port

resources:
  requests:
    # -- cpu requests
    cpu: '50m'
    # -- memory requests
    memory: '100Mi'
  limits:
    # -- cpu limits
    cpu: '200m'
    # -- memory limits
    memory: '400Mi'

metrics:
  # -- should prometheus scrape this server
  enabled: true
  # -- a path prometheus should scrape metrics from
  path: /metrics

auth:
  # -- should use authentication
  enabled: false
  # -- sasl username
  saslUsername:
  # -- sasl password (not encrypted)
  saslPassword:
  secrets:
    # -- should mount secrets to opaque secrets
    useOpaqueSecrets: true
    # -- should use truststore
    useTrustsore: false
    gcp:
      # -- gcp secret resource for sasl password
      saslPasswordResource:
      # -- gcp secret resource for truststore file
      truststoreResource:
      # -- gcp secret resource for truststore password
      truststorePasswordResource:
    vault:
      # -- vault secret path for sasl password
      saslPasswordSecretPath:
      # -- vault secret key for sasl password
      saslPasswordSecretKey:
      # -- vault secret path for truststore file
      truststoreSecretPath:
      # -- vault secret key for truststore file
      truststoreSecretKey:
      # -- vault secret path for truststore password
      truststorePasswordSecretPath:
      # -- vault secret key for truststore password
      truststorePasswordSecretKey:
